name: nodeseek-signin

on:
  workflow_dispatch:
    inputs:
      repo_source:
        description: 'Repo Branch / Tag / Commit ID'
        default: 'master'
        required: true
      docker_tags:
        description: 'Docker Tags (seperate with comma)'
        default: 'latest'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Handle Docker Tags
        run: |
          WORKFLOW_NAME="${{ github.workflow }}"
          IFS=',' read -r -a TAG_ARRAY <<< "${{ github.event.inputs.docker_tags }}"
          TAGS=""
          for TAG in "${TAG_ARRAY[@]}"; do
            TAGS="$TAGS,${{ secrets.DOCKERHUB_USERNAME }}/$WORKFLOW_NAME:$TAG"
          done
          TAGS=${TAGS:1}
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: https://github.com/yowiv/NodeSeek-Signin.git#${{ github.event.inputs.repo_source }}
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.TAGS }}
